// <auto-generated />
using System;
using CP1_Academia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CP1_Academia.Infrastructure.Migrations
{
    [DbContext(typeof(AcademiaContext))]
    partial class AcademiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AulaExtraFichaTreino", b =>
                {
                    b.Property<Guid>("AulaExtrasId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("FichaTreinosId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("AulaExtrasId", "FichaTreinosId");

                    b.HasIndex("FichaTreinosId");

                    b.ToTable("FichaTreinoAulasExtras", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("PlanoId1")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.HasIndex("PlanoId1");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.AulaExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Capacidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("FichaTreinoId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("HorarioAula")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TipoDeAula")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("AulaExtras", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.FichaTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Exercicios")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("MusculoAlvo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<int>("Repeticoes")
                        .HasMaxLength(2)
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Series")
                        .HasMaxLength(2)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoExercicio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("FichaTreino", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<DateTime>("DataDeContratacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid>("GerenteId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<double>("Salario")
                        .HasMaxLength(5)
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<Guid>("UnidadeAcademiaId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("GerenteId");

                    b.HasIndex("UnidadeAcademiaId");

                    b.ToTable("Funcionarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Localizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UnidadeAcademiaId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeAcademiaId")
                        .IsUnique();

                    b.ToTable("Localizacao", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("DataDeAssinatura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataDeRenovacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Fidelidade")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double>("Preco")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TipoPlano")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.HasKey("Id");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.RedeAcademia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QntdUnidades")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("RedeAcademia", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.UnidadeAcademia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<Guid>("GerenteId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("HorarioFuncionamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("LocalizacaoId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("LocalizacaoId1")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RedeAcademiaId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GerenteId");

                    b.HasIndex("LocalizacaoId1");

                    b.HasIndex("RedeAcademiaId");

                    b.ToTable("UnidadeAcademia", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Gerente", b =>
                {
                    b.HasBaseType("CP1_Academia.API.Domain.Entities.Funcionario");

                    b.Property<string>("AreaDeResponsabilidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<double>("Comissao")
                        .HasMaxLength(5)
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("NivelDeLideranca")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<DateTime>("PeriodoDeLideranca")
                        .HasColumnType("TIMESTAMP(7)");

                    b.ToTable("Gerentes", (string)null);
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Instrutor", b =>
                {
                    b.HasBaseType("CP1_Academia.API.Domain.Entities.Funcionario");

                    b.Property<string>("Cref")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)");

                    b.ToTable("Instrutor", (string)null);
                });

            modelBuilder.Entity("AulaExtraFichaTreino", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.AulaExtra", null)
                        .WithMany()
                        .HasForeignKey("AulaExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP1_Academia.API.Domain.Entities.FichaTreino", null)
                        .WithMany()
                        .HasForeignKey("FichaTreinosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.Plano", null)
                        .WithMany("Alunos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP1_Academia.API.Domain.Entities.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.FichaTreino", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.Aluno", "Aluno")
                        .WithOne("FichaTreino")
                        .HasForeignKey("CP1_Academia.API.Domain.Entities.FichaTreino", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.Gerente", "Gerente")
                        .WithMany("Funcionarios")
                        .HasForeignKey("GerenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP1_Academia.API.Domain.Entities.UnidadeAcademia", "UnidadeAcademia")
                        .WithMany("Funcionarios")
                        .HasForeignKey("UnidadeAcademiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gerente");

                    b.Navigation("UnidadeAcademia");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Localizacao", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.UnidadeAcademia", "UnidadeAcademia")
                        .WithOne()
                        .HasForeignKey("CP1_Academia.API.Domain.Entities.Localizacao", "UnidadeAcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeAcademia");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.UnidadeAcademia", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.Gerente", "Gerente")
                        .WithMany("UnidadesAcademia")
                        .HasForeignKey("GerenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP1_Academia.API.Domain.Entities.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP1_Academia.API.Domain.Entities.RedeAcademia", "RedeAcademia")
                        .WithMany("UnidadesAcademia")
                        .HasForeignKey("RedeAcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gerente");

                    b.Navigation("Localizacao");

                    b.Navigation("RedeAcademia");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Gerente", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.Funcionario", null)
                        .WithOne()
                        .HasForeignKey("CP1_Academia.API.Domain.Entities.Gerente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Instrutor", b =>
                {
                    b.HasOne("CP1_Academia.API.Domain.Entities.Funcionario", null)
                        .WithOne()
                        .HasForeignKey("CP1_Academia.API.Domain.Entities.Instrutor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("FichaTreino")
                        .IsRequired();
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Plano", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.RedeAcademia", b =>
                {
                    b.Navigation("UnidadesAcademia");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.UnidadeAcademia", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("CP1_Academia.API.Domain.Entities.Gerente", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("UnidadesAcademia");
                });
#pragma warning restore 612, 618
        }
    }
}
